apiVersion: v1
kind: ConfigMap
metadata:
  name: express-kafka-config
data:
  PORT: "3000"
  KAFKA_BROKER: "kafka-service:9092"
  KAFKA_CLIENT_ID: "express-kafka-client"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  OTEL_SERVICE_NAME: "express-kafka-api"
  LOG_LEVEL: "info"